### ISSUE TITLE
Wire emergency stop and make sure it works

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#115]
The emergency stop is already wired but not connected. As it is hard to reach and will open when pressed, we could add another one in the same loop, but reachable without effort.

**Comment by MichelDC** [comment]
I added an emergency stop (with a big fat red button), built a box, wired it and it actually works
![emergencystopbox](https://user-images.githubusercontent.com/29261712/26897642-8058031c-4bc9-11e7-9ea3-6675e46d26ac.png)

**Comment by emka** [comment]
That is awesome, thank you!
