### ISSUE TITLE
take photos of hardware for the wiki

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/do-something#12]
Many tools, machines and materials have wiki pages already but the InfoBoxes are lacking a picture

**Comment by emka** [comment]
List of pages currently missing pictures (checkmark means picture added):
- [ ] Dremel
- [ ] Screwdrivers
- [ ] Cordless Drill (Makita)
- [ ] Soldering Irons
- [ ] Disc Grinder
- [ ] Caliper
- [ ] Screwdriver Bits
- [ ] Twist Drill Bits
- [ ] Hole Saws
- [ ] Jigsaw
- [ ] Eccentric Sander
- [ ] Router
- [ ] Pyrography Burner
- [ ] Hex Keys

**Comment by emka** [comment]
We took pictures of all above, still need to upload.

**Comment by LukasFreeze** [comment]
to see pages that have InfoBoxes without pictures, check out these links:

- [tool pages without a picture](https://wiki.heidelberg-makerspace.de/wiki/Special:WhatLinksHere/File:Tool-default.png)
- [machine pages without a picture](https://wiki.heidelberg-makerspace.de/wiki/Special:WhatLinksHere/File:Machine-default.png)
- [material pages without a picture](https://wiki.heidelberg-makerspace.de/wiki/Special:WhatLinksHere/File:Material-default.png)
- and, maybe less relevant, [project pages without a picture]((https://wiki.heidelberg-makerspace.de/wiki/Special:WhatLinksHere/File:Project-default.png)

**Comment by emka** [comment]
Old list is done, but Lukas linked many new pages (see above comment)

**Comment by emka** [comment]
Took photos of all missing tools and machines that had an InfoBox. Materials are still missing, and I would ignore project pages as these are in responsibility of the project team.

**Comment by emka** [comment]
All uploaded, tool pages are currently complete, the only missing machine page is the not yet delivered Laser Cutter.

**Comment by emka** [comment]
Took more photos and added them to our wiki. Only two special materials are missing:
- [ ] Copper tape
- [ ] Fender washers

**Comment by emka** [comment]
Took more photos today, unfortunately only in RAW format...

**Comment by LukasFreeze** [comment]
I'm uploading about 15 new tool pictures, some don't have the _perfect_ depth of field but it was getting pretty late... I did not take too many material pictures this time.

**Comment by emka** [comment]
Converted the RAW images and added them. I will add your links from [above](https://github.com/heidelberg-makerspace/do-something/issues/12#issuecomment-234102666) to the README as there will always be more.

**Comment by emka** [comment]
This is a permanent issue as there will always be newly created wiki pages, added to the README.
