### ISSUE TITLE
repair & string guitar

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/do-something#121]
The DAI Sprachschule donated a guitar to us! Unfortunately, it has no functional bridge or strings anymore.

* [x] repair bridge & replace pins (or whatever they are called)
* [x] buy strings
* [x] string, tune, start playing

 You can get reimbursed for parts you need to buy, just talk to me!

**Comment by HerrBaumhaus** [comment]
Hi, I glued in the bridge using UHU "Endfest" 2-Component Epoxy-Glue. I hope in that way the sound propagation will be optimal.
I found fitting strings in the  guitar bag, so the guitar is ready for a final tuning now.

Have fun :)
