### ISSUE TITLE
table saw fence locking handle is broken

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/do-something#127]
During the redecorating before (or after?) the "OK Lab" event today, someone broke off the plastic handle on the table saw fence so it can't be used right now...

Laser cutting a turnwheel out of thick acrylic glass might be a nice option that would stick out less and be less prone to being broken again - or perhaps the existing handle can be fixed with a special material @jasperclaudio had in mind.

**Comment by jasperclaudio** [comment]
I fixed the handle using a moldable thermo-plastic. Works just like before...
