### ISSUE TITLE
disable wiki spam filter

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/do-something#129]
There appears to be a spam filter in our wiki, preventing the addition of aliexpress links for example.

Since we already keep a tight control over which users get editing rights, disabling it altogether should be easier than adding exceptions now and then.

**Comment by chombium** [comment]
I think it would be better if the spam filter stays active. We should only adjust the Spam filter's whitelist here https://wiki.heidelberg-makerspace.de/wiki/MediaWiki:Spam-whitelist

**Comment by emka** [comment]
Added aliexpress.com to the whitelist as @chombium suggested. @LukasFreeze should have these permissions as well. Please test if that worked and also include the link that was blocked here if it still does not work, then I can test it myself.

**Comment by LukasFreeze** [comment]
@PaulGoldschmidt, could you try your original link (without "kurzelinks.de" again?

**Comment by LukasFreeze** [comment]
I confirmed that it works now, thanks!
