### ISSUE TITLE
remove RZL sticker from Makerspace banner

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/do-something#13]
some joker put a sticker reading "eine Veranstaltung des RZL" onto our banner (the one standing by the main entrance - that needs to be gone by the 2nd of July!

- [x] try bare hands & patience - failed
- [ ] try warm soapy water
- [ ] try alcohol ("Brennspiritus")
- [ ] try acetone - careful, could damage the material!

**Comment by Pakue95** [comment]
Johannes has removed it as far as I know. You can close the issue if you want. Btw. acetone damages the banner (tested it on the backside).

**Comment by emka** [comment]
Plain water worked to remove the paper part, the glue is still on there.
