### ISSUE TITLE
label our equipment

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/do-something#18]
Lots of Makerspace tools could still use a "Makerspace" label and/or one that names the corresponding wiki page (have a look at the Makita drill as an example). Not everything can be labeled with the Labelmaker though, and unfortunately the labels currently don't stick...

- [x] create "Labelmaker" wiki page
- [x] find a way to use non-sticking portion of the current label cassette (i.e. a suitable glue to use it with)
- [ ] label tools/furniture/power cords that **definitely** belong to the Makerspace

**Comment by emka** [comment]
The current label cassette actually works as intended, it is just difficult to remove the non-sticking part. Luzian is able to remove it.

**Comment by emka** [comment]
I labeled a few things, it is difficult to tell what is missing.

**Comment by emka** [comment]
@LukasFreeze, can we close this one?

**Comment by LukasFreeze** [comment]
I suppose we can, it's too vague anyway :-P

Let's keep in mind the labelmaker exists whenever we find something "new"
