### ISSUE TITLE
Build bookshelf

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#2]
- [x] Rough cut of shelves
- [x] Fine cut of edges to fit the wall
- [x] Mark shelf positions
- [x] Drilling holes
- [x] Mount shelves

**Comment by emka** [comment]
Just one shelf missing, the rest is on the wall.

**Comment by LukasFreeze** [comment]
done! documentation found under "[Makerspace Bookshelf](https://wiki.heidelberg-makerspace.de/wiki/Makerspace_Bookshelf)" on the wiki.
