### ISSUE TITLE
bring old laptop battery (and other stuff) to recycling center

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/do-something#20]
There is an old laptop battery in the green metal drill box that should ideally be brought to a recycling center before it explodes. While you're at it, please empty the metal junk bucket and e.Waste as well ;-)

**Comment by emka** [comment]
We have two bags of demolition rubble as well which are currently occupying storage space.

**Comment by Pakue95** [comment]
[Here](http://www.heidelberg.de/hd,Lde/HD/Rathaus/Recyclinghoefe.html#standorte-und-regulre-ffnungszeiten) are some places around Heidelberg which can take the waste. The one in Kirchheim seems to be the easiest to get to. They are all free as long the amount is below one m<sup>3</sup>. 
We'll probably need a car for this.

**Comment by LukasFreeze** [comment]
let's call it "renovation rubble", okay? ;-)

But yes, we *definitely need a car*

**Comment by emka** [comment]
What about the door? Should it also go there?

**Comment by LukasFreeze** [comment]
Yes, but if only a regular car is available we could sit on the door a little longer but get rid of the rest

**Comment by emka** [comment]
Patrick and I brought everything except the door to the recycling center. The "non-recyclable renovation rubble" cost us a small fee. Done just in time before Sofienstraße will be closed completely.

**Comment by LukasFreeze** [comment]
Thanks a lot guys & enjoy your Merit Mate!
