### ISSUE TITLE
remove lock from laser room door

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/do-something#22]
The white steel door that used to sit in the power tool hangar could become the laser room door but has a lock we do not have keys for. Lukas has a replacement lock lying around but to exchange it, the old lock has to be opened once.

Nico has tried to pick the lock but was so far unsuccessful. We should keep trying at leat for a while as it would be the most elegant way of removing the lock (short of finding the actual key, of course).

**Comment by emka** [comment]
The janitor tried many keys and was able to remove the lock. New lock is installed.
