### ISSUE TITLE
list library books on the wiki

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/do-something#23]
Besides our [Makerspace bookshelf](https://wiki.heidelberg-makerspace.de/wiki/Makerspace_Bookshelf), there are many interesting books and magazines two stories up in the DAI library! It would be great if there was a list of these titles on the ["Library" wiki page](https://wiki.heidelberg-makerspace.de/wiki/Library) - please transcribe the titles from the photo already on the page.

**Comment by emka** [comment]
All books in the maker shelf have signature (Signatur) "MAK *", but I could not figure out how to search for that in the library online catalog. I asked Rebekah for advice how to run this kind of search.

**Comment by LukasFreeze** [comment]
Mitja added the information on how to search the library catalogue to the wiki.
