### ISSUE TITLE
Create ToolInfoBoxes

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#31]
I uploaded many pictures today, but the articles still need ToolInfoBoxes and more text.

Check today's recent changes for a list, I will still upload a few more today.

**Comment by LukasFreeze** [comment]
unresolved stubs Mitja is referring to (minus the ones I continued today):
- [ ] Coffee Machine (needs MachineInfoBox, but same general idea)
- [ ] Paper Cutter
- [ ] IFixIt Pro Tech Toolkit
- [ ] Material:Stone (needs MaterialInfoBox)
- [ ] Hot Glue Gun
- [ ] Spatulas
- [ ] Sensor Kit
- [ ] Scale
- [ ] Level
- [ ] Pincers
- [ ] Taps and Dies
- [ ] Hammers
- [ ] Material:Acrylic Glass (needs MaterialInfoBox)
- [ ] Material:Plywood (needs MaterialInfoBox)
- [ ] Knives
- [ ] Files

**Comment by emka** [comment]
All of these pages now have InfoBoxes. Of course they could need more text.
