### ISSUE TITLE
Create a table for the USB hub we'll connect the entry raspi to.

### ISSUE THREAD

**Issue by Pakue95** [heidelberg-makerspace/do-something#33]
Thanks to "Markuhn" we now got a fancy OPEN/CLOSED lever with API for our Makerspace. However it needs power for a Raspberry Pi so we ordered a 10 port 60W USB charger as power supply. This is certainly overkill for one Pi but the idea is to use it as a "charging center" for phones and similar.

- [x] create a nice table/phone rest to support the charger and secure it from any inappropriate use.

**Comment by emka** [comment]
There is a [project page](https://wiki.heidelberg-makerspace.de/wiki/Project:Powertable) in our wiki now.

**Comment by Pakue95** [comment]
The charger is installed and is located at the entrance. An idea was to add some lighting in the two boxes of the table. However this is not an essential addition therefore I'll close this issue.
