### ISSUE TITLE
attach cloth to ceiling in Stepcraft room

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#39]
There is sand coming off the ceiling in the Stepcraft room, which is really bad for the mechanics. To protect it, we can attach cloth to the ceiling at the lamp and staple it to the wooden walls.

Open questions:
- [x] Do we have a suitable stapler?
- [x] Which cloth can we use, does it need to be fire resistant?
- [x] How to attach it to the ceiling?

When answered, get the cloth and attach it.

**Comment by LukasFreeze** [comment]
The stapler on the pegboard should be fine, I used it for the Power Tool Hangar door as well. I think we should be able to use any cloth as long as it is fixed at the base of the lamp fixture and has no risk of touching the (anyways rather cold) tube itself.

**Comment by emka** [comment]
White or similar might be best to reflect light downwards.

**Comment by emka** [comment]
@YannickDupps will bring some fire-resistant black cloth. White would be much more expensive.

**Comment by LukasFreeze** [comment]
In case he would have to buy that - we could use some of the Molton (black, fire resistant) fabric in the sewing corner! There is a very big piece :-)

**Comment by YannickDupps** [comment]
I wouldn't have to buy it but if you already have black Molton at the Makerspace we could use that since it's the same thing as I wanted to bring.

**Comment by LukasFreeze** [comment]
alright, then I'll see if we can get it done tomorrow during the sewing café!

**Comment by LukasFreeze** [comment]
Done! Thanks @beanobeano and @YannickDupps for a lot of help.

We ended up just cutting the fabric to roughly the right size and trimming it after it was attached. We mounted a board under the lamp fixture to bear the main weight (the original mounting holes were terrible anyway, now there aremuch bigger screws and wall anchors in there)

**Comment by LukasFreeze** [comment]
Oh, one more thing: it's a bit darker now, but we can make a reflector if needed (not _too_ hard to take the lamp down again)
