### ISSUE TITLE
Label the light switches

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#4]
It is currently impossible to tell which light belongs to which button at the entrance.

- [x] Find proper names for all light locations
- [x] Put labels next to the appropriate buttons at the entrance
- [x] Print a 3D map with the names and lights (Lukas modeled the room already)

**Comment by emka** [comment]
Names must be short (no space), suggestions: "Bar", "Entrance", "Sewing", "Maker Shelf".

**Comment by LukasFreeze** [comment]
sounds good - would "Bar Front" still fit? Because one of the other switches controls the lights behind the bar (maybe "Photo Corner" or "Bar Back"?)
There is also one for the drinks room, could just be "Hands Off" imho ;-)

**Comment by emka** [comment]
we could only identify the four switches for the main room, the others can be added easily once identified

**Comment by LukasFreeze** [comment]
labeled the rest, 3D plan coming soon!

**Comment by LukasFreeze** [comment]
done! 3D [top view of empty room](https://wiki.heidelberg-makerspace.de/wiki/File:Makerspace_empty_top_view.PNG) with lights drawn in is printed and on the wall above the switchbox :-)
