### ISSUE TITLE
Laser cutter donation box

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#41]
We have separate donation boxes for several activities like sewing, 3d printing and workshop to allow designated funds. The laser cutter should get its own box, ideally manufactured using the laser cutter.

- [x] Design a box (with a lock).
- [x] Assemle it.
- [x] Mount it near the laser cutter (but accessible from outside when the door is closed).
- [x] Find a lock

**Comment by emka** [comment]
Paul volunteered to design something and send us the files as he can not attend next Wednesday.

**Comment by emka** [comment]
Paul designed one today and we cut it. Still needs assembly, a hinge and the metal locking part.

**Comment by emka** [comment]
I glued the parts together. The design did not account for the thickness of of the material correctly and did not include a hinge, but the box is working for now. I 3d printed the part for a lock and added a hinge. We still need a lock, otherwise the box is operational.
![img_20160810_202915](https://cloud.githubusercontent.com/assets/48825/17567045/11f2ebbc-5f3e-11e6-9294-99c5f8183474.jpg)

**Comment by emka** [comment]
Patrick brought a lock. When the box is locked, it can be bent on the bottom and all content can be removed. We need a better box design.

**Comment by LukasFreeze** [comment]
I'll try to take care of it this week :-)

**Comment by LukasFreeze** [comment]
@Pakue95 made and mounted one today, only needs to be added to the Wiki now!
