### ISSUE TITLE
Buy CO2 fire extinguisher

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#43]
We need a 5-6kg CO2 fire extinguisher for #40, where can we get it? One option would be Ebay for approx. 70 EUR. It should have been tested recently to avoid additional cost or malfunction.

**Comment by emka** [comment]
I will check out the store opposite of Bauhaus in Eppelheim.

**Comment by emka** [comment]
The [shop I was talking about](http://www.fliesen-kamine-heidelberg.de/) turned out to be closed due to holiday until 29.8. but it is selling completely different products.

Bauhaus does not sell any CO2 extinguishers at all.
There might be a specialized shop in Weinheim, but I think we should just order on Ebay. @LukasFreeze what do you think?

There is one CO2 fire extinguisher in the kitchen, we could also try to find out which company the DAI is using for servicing.

**Comment by LukasFreeze** [comment]
ebay sounds good, better to have this soon than to wait around for a possibly maybe okay-ish local option in this case :-P
As far as the DAI goes, we should team up with Mathias to push for better extinguishers in the whole building (powder /foam instead of water...)

**Comment by emka** [comment]
Ordered a new 5kg one from a shop in Speyer

**Comment by emka** [comment]
It arrived and is located at the laser room door, could be used on the e-bench or 3d printers as well.
