### ISSUE TITLE
Install and mount compressor

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#44]
Install and mount the designated compressor for the laser cutter. According to its manual the connector is on the back, might be hard to reach.

**Comment by LukasFreeze** [comment]
a longer pneumatic tube will most likely be needed as well, do you know the diameter yet?

**Comment by Pakue95** [comment]
The manual states 0,25" (6mm) at page 71. On Amazon a pneumatic tube this size (5m) costs about 11€ rated for 15bar (6x max pressure). If I ordered tonight it would arrive until Wednesday.

**Comment by LukasFreeze** [comment]
sounds good! We can always shorten it later once we know where exactly the compressor can go. Make sure to keep the receipt as always ;-)

**Comment by Pakue95** [comment]
Ok tube is ordered!

**Comment by emka** [comment]
Tube is mounted, works much better with compressor turned on!
