### ISSUE TITLE
Create VisiCut settings

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#46]
Create and push default VisiCut settings to Github and [send a pull request](https://github.com/t-oster/VisiCut/wiki/How-to-add-default-settings-for-your-lab)

**Comment by emka** [comment]
Patrick was able to use the laser cutter with Visicut on a Macbook. We are able to cut from all major platforms!

**Comment by Pakue95** [comment]
I've got a profile for our laser cutter running on my laptop which works nicely. Only the estimated time is far off as the Helix driver is used, which is a slower cutter than our Legend 36EXT. I haven't found the speed settings for the axis in the driver yet. For the non-Epilog laser cutters there is an option for this.
Also I'd like to wait for to laser cutter to work flawlessly before publishing the profile.

**Comment by emka** [comment]
We could put the current profile in the repository anyway before everyone starts from scratch.

**Comment by Pakue95** [comment]
Repository is up! See /heidelberg-makerspace/visicut-settings/
