### ISSUE TITLE
Bring door to recycling center

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#47]
We need someone with a larger car to bring the old door behind the photo booth to a [recycling center](http://www.heidelberg.de/hd,Lde/HD/Rathaus/Recyclinghoefe.html#standorte-und-regulre-ffnungszeiten).

**Comment by LukasFreeze** [comment]
Jasper is taking care of it :-)

**Comment by jasperclaudio** [comment]
...Jasper took care of it 😉

**Comment by LukasFreeze** [comment]
Thanks, did it cost anything? You can get that back!

**Comment by jasperclaudio** [comment]
Nope - was for free!

> Am 21.12.2016 um 05:32 schrieb Lukas <notifications@github.com>:
> 
> Thanks, did it cost anything? You can get that back!
>
