### ISSUE TITLE
Build middle and upper e.Bench shelfs

### ISSUE THREAD

**Issue by Pakue95** [heidelberg-makerspace/do-something#5]
- [x] middle shelf
- [x] upper shelf

**Comment by emka** [comment]
Patrick, could you finish that one tomorrow? The e.Bench is moved aside anyways so it is very accessible at the moment. I can help as long as there are not too many visitors needing my attention.

**Comment by emka** [comment]
I found only one piece of wood that would fit for both. The bottom side is not that beautiful, but it should work. Labeled it as designated for eBench, but did not cut anything yet.

**Comment by emka** [comment]
Patrick fitted the shelves but we still need to build a drawer sliding mechanism to better reach them.

**Comment by Pakue95** [comment]
Mitja and I finished the shelves today (finally). e.Bench is so far hardware-wise done.
