### ISSUE TITLE
Air duct part behind laser cutter

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#51]
The current tube mount occupies too much space behind the laser cutter. We need a flat part with identical fitting to save some space and be able to move the laser cutter closer to the wall.

**Comment by emka** [comment]
We have some ![exhaust measures](https://cloud.githubusercontent.com/assets/48825/17750365/5e6c4f90-64c2-11e6-9809-a56e68ed30ea.jpg) now. The biggest one I could find has a [12.5mm diameter](http://www.hornbach.de/shop/Flachkanal-Umlenkstueck-Rotheigner-weiss-220x54-mm-mit-Stutzen/8610784/artikel.html).

Lukas took a picture of a custom construction in another makerspace.

**Comment by emka** [comment]
![one](https://cloud.githubusercontent.com/assets/48825/17750528/35e2dca0-64c3-11e6-95d2-e3f3bdf506d2.jpeg)
![two](https://cloud.githubusercontent.com/assets/48825/17750529/35e50426-64c3-11e6-91ab-5fe904e2e23f.jpeg)

**Comment by LukasFreeze** [comment]
André and I measured the hose today and "d" in the above drawing seems to be wrong - we got 10 cm (without rubber seal), could that be? Maybe this means we'll find a readily available solution!

**Comment by emka** [comment]
No, there is an additional piece of metal attached on the one I have drawn. It reduces the diameter from "d" to 10cm. Maybe we could start with 10cm anyway instead of reducing it later, but that might cause some particles being stuck between the larger hole on the laser cutter and our custom plate. Another question for support ;)

**Comment by LukasFreeze** [comment]
Although the installing technician said 10 cm room in the back were enough, today I was told to leave 20 - 30 cm to prevent overheating. This may eliminate the need for a flatter solution but we can still try to solve this issue for aesthetic reasons and as an experiment...

**Comment by LukasFreeze** [comment]
Current distance to the wall is 26 cm, so we don't really have room for improvement according to the tech.
