### ISSUE TITLE
Fat on camera lens

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#55]
The DSLR lens had fat on it, we discovered that some time ago. Somehow we lost track of it (no issue created here).

Patrick knows how to clean it and will take care of it.

**Comment by emka** [comment]
Lens was cleaned.

**Comment by LukasFreeze** [comment]
Great - a how-to on the DSLR wiki page (which does not exist yet...) would be nice so we can take immediate care of it next time!
