### ISSUE TITLE
Ceiling mount for projector

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#59]
Build a lockable ceiling mount for the [projector](https://wiki.heidelberg-makerspace.de/wiki/Projector). Mount it to the ceiling in the optimal distance for our screen.

**Comment by LukasFreeze** [comment]
--- HOLD UNTIL FURTHER NOTICE ---
Apparently, the roller blind we are using as a screen has to be mounted further from the windows for safety reasons. The projector can not be mounted anywhere until this is clear (only heard about it today by chance...)

**Comment by LukasFreeze** [comment]
We'll have to move the screen forward a bit, then we can see where to mount the projector. Hopefully it will still be possible without reducing the image size...

**Comment by LukasFreeze** [comment]
Took the screen down today, hopefully able to re-mount it next week. Whoever had mounted it first did a terrible job, we'll have a more stable solution soon...

**Comment by LukasFreeze** [comment]
The screen is re-mounted about a meter further into the room but there should still be spots to place the projector for a good image size. Went for a location slightly to the right of the room so the emergency light and power supply chain in the center won't get in the way.

**Comment by LukasFreeze** [comment]
I have access to ladders and @Pakue95 will bring in a ball joint from an old camera mount soon, so we are nearly ready to get started on this!

**Comment by Pakue95** [comment]
The mount for the projector is finished so far. We just need to drill holes in the ceiling and mount a piece of wood to screw the quick release into.

**Comment by Pakue95** [comment]
Beamer sits and fits on the ceiling. HDMI and power cables are installed.
We should consider removing the boxes on top of the rollable shelf and convert it to the presentation/video laptop spot. Some general adapters (VGA, USB-C, miniDisplayPort etc.) to HDMI would also be a nice addition. Nevertheless this issue is done. *yay*

**Comment by LukasFreeze** [comment]
The file cabinet is a better option for the "laptop station" as the presenter can stand there during a talk. We could also store the adapters you mentioned in that cabinet (if we have money or the parts themselves donated...) ;-)
