### ISSUE TITLE
3D Printer emergency switches

### ISSUE THREAD

**Issue by JohannesGruhler** [heidelberg-makerspace/do-something#61]
we need emergency switches for the Prusa i3 printers.

- [x] 3D print cases
- [x] test switches Ciaran donated
- [x] install (cutting the 12 V supply, not mains voltage)

**Comment by emka** [comment]
I think they are done, @JohannesGruhler is there anything left to do?

**Comment by JohannesGruhler** [comment]
perhaps emergency switch for Kossel B, but first we need to make issue #62 (Kossel B rewiring).

**Comment by LukasFreeze** [comment]
As far as I remember the new Kossel power supplies should have switches on them, we could just engrave an arrow or similar into the new cases (see #62 for progress) and not buy any further emergency buttons.

@JohannesGruhler could now add the switches to the lists of modifications on the Prusas' wiki pages and this could be closed :-)
