### ISSUE TITLE
Kossel B rewiring

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/do-something#62]
Andrea is redoing the wires of the [Kossel B](https://wiki.heidelberg-makerspace.de/wiki/Kossel_B) as it could use a better power supply and the original wires are too short in some places.
- [x] feet for the whole printer - @emka is 3D printing the bases, we'll use M6 x 50 (or 60) mm hex-head screws that screw directly into the aluminium extrusions
- [x] case for power supply - @emka is cutting the wooden parts
- [x] wiring once power supply is re-established

**Comment by emka** [comment]
I gave the feet design to Andrea, she will print them and prepare the screws.

**Comment by LukasFreeze** [comment]
Andrea attached the feet and an HDF baseplate (cut by Johannes with the scroll saw) for the board to sit on. Rewiring will hopefully happen next week.

**Comment by emka** [comment]
I cut parts for the case with the jigsaw. Some dimensions were a bit off and we will redo it with thinner wood on the table saw.

**Comment by LukasFreeze** [comment]
rewiring should be finished next week!

**Comment by emka** [comment]
Andrea finished the rewiring and printed a calibration cube. She took the wooden parts home to glue them, probably done tomorrow.

**Comment by emka** [comment]
All done. There are just a few optional improvements remaining like a red circle around the power button and smoothed out corners.

**Comment by LukasFreeze** [comment]
one more thing, sorry: added full metal Z probe and calibrated today, test print pending

**Comment by JohannesGruhler** [comment]
Kossel B update 
- I removed the objekt fan because of (the fan was to big and to strong the nossel had problems to heat up)
- I replaced the Polyimide Tape
- I oiled the autoleveling construction with WD-40 (problems with the trigger)

**Comment by LukasFreeze** [comment]
...and, most importantly, a firmware re-flash got the bed leveling to work again!

@JohannesGruhler, how did your test print turn out? You can close this issue if you were satisfied ;-)

**Comment by Johannes09** [comment]
There are new problem's with the extruder and I am designing new parts for it.

**Comment by Johannes09** [comment]
with the new extruder kossel B prints good results
