### ISSUE TITLE
Mount CO2 fire extinguisher to the wall

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#65]
Mount CO2 fire extinguisher to the wall. Must be done by Lukas as it requires drilling.

**Comment by LukasFreeze** [comment]
We need to rethink the location first, if we mount it in front of the exhaust filter the remote does not work...

**Comment by LukasFreeze** [comment]
Was there a mount that came with it? Thought anout drilling today but couldn't find anything...

**Comment by emka** [comment]
Yes, the mount is in the same drawer as our label maker.

**Comment by LukasFreeze** [comment]
Ah, alright. Next time then!

**Comment by LukasFreeze** [comment]
Done! The holder is not supporting the extinguisher enough to keep it from touching the wall, but it's better this way than changing it and risking to have it fall off the wall...
