### ISSUE TITLE
fill gaps between floor tiles and walls

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/do-something#7]
There is an annoying gap around the floor tiles in the back rooms, allowing tables to fall in and dirt to accumulate. We have already taken care of the most urgent spots and used about 15 kg of cement (more under the milling table).

- [x] milling corner
- [x] laser room
- [x] 3D printer farm 
- [x] e.Bench

**Comment by LukasFreeze** [comment]
almost done, Ciaran is unstoppable! :-D

**Comment by emka** [comment]
Done
