### ISSUE TITLE
Pfaff creative 1.5 bobbin spooler doesn't turn

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/do-something#82]
The bobbin spooler (little pin on the right at the top of the machine) of the Pfaff creative 1.5 sewing machine does not turn under workload and only veeeery slow without a bobbin on it.

Opening the top cover is not trivial so we will talk to the people at the store before voiding warranty!

**Comment by LukasFreeze** [comment]
Apparently the spooling did use to work at some point (at least when the machine was brand new), will go to the store soon if I have time...

**Comment by LukasFreeze** [comment]
There were more problems, e.g. somebody apparently opened the machine's "Stichplatte" and let a screw fall into the mechanics! That's great...machine is on its way to the manufacturer.

**Comment by jasperclaudio** [comment]
Die Maschine ist wieder da mit einer erweiterten Garantie auf Ersatzteile! Bitte sorgsam mit ihr umgehen und am besten nur in Anwesenheit eines*r erfahren*en Benutzer*in verwenden... es ist jetzt schon das zweite Mal dass wir sie in die Werkstatt bringen mussten.
