### ISSUE TITLE
Fix Prusa B Z-probe

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#83]
The Prusa B Z-probe crashed into the bed again and was slightly tilted. Needs recalibration and some effective way to avoid that it is crashing.
I had the impression that Prusa A is moving much slower in Z-direction towards the bed.

**Comment by Pakue95** [comment]
It's weird that this only happens relatively irregular.. Maybe a slower Z-Speed would help but maybe the induction probe has a fault.

**Comment by LukasFreeze** [comment]
Or the connection to the board...

**Comment by beanobeano** [comment]
Issue resolved. Re-calibrated and tested.

**Comment by emka** [comment]
I created a "Members" team and gave write permission to this team. You should be able to close it now.

**Comment by beanobeano** [comment]
Thanks! Closing it now.
