### ISSUE TITLE
Flash new TinyG PCB

### ISSUE THREAD

**Issue by emka** [heidelberg-makerspace/do-something#91]
Yannick populated a second SC-TinyG Controller PCB, which still needs flashing.

Atmel Studio required a newer firmware version on our PDI programmer (issue #90). This needs to be resolved before we can continue.

**Comment by emka** [comment]
Flashing is done using Atmel Studio, fuses still need to be set.

**Comment by YannickDupps** [comment]
I flashed the current master of TinyG (tinyg-master-440.20) 
Fuses are set according to the picture.
![fuse settings](https://cloud.githubusercontent.com/assets/23366278/20153342/9ac7e70a-a6c2-11e6-8ff8-7d67a81c2608.jpg)

**Comment by emka** [comment]
This version is able to talk to ChiliPeppr (now we are one step further than with the first TinyG PCB), but we could not move the axis. Probably the upstream version needs some modifications.

**Comment by emka** [comment]
The last firmware from the forum is [this one](https://www.stepcraft-systems.com/media/kunena/attachments/1384/TinyG_2014-11-21.zip).

**Comment by emka** [comment]
No luck so far, lets learn more about ChiliPeppr.

**Comment by emka** [comment]
The version numbers can be found in ```tinyg.h```, for the firmware from the forum it is
```
#define TINYG_FIRMWARE_BUILD        380.08
#define TINYG_FIRMWARE_VERSION      0.96
```

I think that should be commit ```d8c700f5cca6d0d33aa0d9c24474d098d968e823``` in the upstream project. I checked out that commit and overwrote the files with those from the forum zip file.

```git diff -w``` shows quite a few changes, I still need to have a closer look what has been changed.

**Comment by emka** [comment]
The flashing part is done and I think we should try that older firmware first, lets continue in issue #97.
